name: Create and publish a container image

on:
  push:
    branches:
      - "main"
    tags:
      - "v*"
  pull_request:

jobs:
  set-variables:
    runs-on: ubuntu-24.04
    permissions: {}
    outputs:
      source-sha-short: ${{ steps.short-sha.outputs.SOURCE_SHA_SHORT }}
    steps:
      - name: Get short Git hash
        id: short-sha
        run: echo "SOURCE_SHA_SHORT=$(echo ${{ github.sha }} | head -c 10)" >> $GITHUB_OUTPUT

  build-and-push-image:
    needs: set-variables
    permissions:
      contents: read
      packages: write
    secrets: inherit
    uses: ./.github/workflows/build-image.yml
    with:
      image-name: plutono
      build-args: |
        SOURCE_GIT_BRANCH=${{ github.ref_name }}
        SOURCE_GIT_REV_SHORT=${{ needs.set-variables.source-sha-short }}
      # it's not possible to access the "secret" context here, so indirectly pass the variable name here
      secrets-github-token-name: NODE_AUTH_TOKEN

  e2e-test:
    needs: build-and-push-image
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      packages: read
    env:
      REGISTRY: ghcr.io
      REGISTRY_IMAGE: ghcr.io/${{ github.repository_owner }}/plutono
      HOST: localhost
      PORT: "3000"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 14.15.5
          cache: yarn
          registry-url: 'https://npm.pkg.github.com'
          scope: '@credativ'

      - name: Install dependencies
        run: yarn install --pure-lockfile --no-progress --network-concurrency 1
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Install cypress
        run: node_modules/cypress/bin/cypress install

      - name: Log in to the container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.REGISTRY_IMAGE }}

      - name: Start server
        run: >
          docker run --detach
          -p 3000:3000
          -e PL_SECURITY_ADMIN_USER=admin -e PL_SECURITY_ADMIN_PASSWORD=admin
          -v $(pwd)/devenv/datasources.yaml:/etc/plutono/provisioning/datasources/datasources.yaml:ro
          -v $(pwd)/devenv/dashboards.yaml:/etc/plutono/provisioning/dashboards/dashboards.yaml:ro
          -v $(pwd)/devenv:/usr/share/plutono/devenv:ro
          ${{ env.REGISTRY_IMAGE }}:${{ steps.meta.outputs.version }}

      - name: Wait for server
        run: e2e/wait-for-plutono

      - name: Run E2E test
        run: e2e/run-suite
